# Generated by Django 5.2.1 on 2025-05-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0004_alter_product_excise_duty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='inn',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='kpp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='manager_fio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='relation_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_type',
            field=models.CharField(max_length=20),
        ),
    ]
