# Generated by Django 5.2.1 on 2025-05-28 01:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0016_rename_number_invoice_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True)),
                ('inn', models.CharField(blank=True)),
                ('kpp', models.CharField(blank=True)),
                ('address', models.CharField(blank=True)),
                ('manager', models.CharField(blank=True)),
                ('manager_fio', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True)),
                ('name', models.CharField(blank=True)),
                ('inn', models.CharField(blank=True)),
                ('kpp', models.CharField(blank=True)),
                ('address', models.CharField(blank=True)),
                ('manager_fio', models.CharField(blank=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upd.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True)),
                ('name', models.CharField(blank=True)),
                ('inn', models.CharField(blank=True)),
                ('kpp', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True)),
                ('name', models.CharField(blank=True)),
                ('inn', models.CharField(blank=True)),
                ('kpp', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True)),
                ('name', models.CharField(blank=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('other', models.CharField(blank=True)),
                ('resp_position', models.CharField(blank=True)),
                ('resp_name', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True)),
                ('name', models.CharField(blank=True)),
                ('full_name', models.CharField(blank=True)),
                ('inn', models.CharField(blank=True)),
                ('kpp', models.CharField(blank=True)),
                ('reg_address', models.CharField(blank=True)),
                ('address', models.CharField(blank=True)),
                ('requisite', models.CharField(blank=True)),
                ('manager', models.CharField(blank=True)),
                ('manager_fio', models.CharField(blank=True)),
                ('accountant_fio', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True)),
                ('name', models.CharField(blank=True)),
                ('inn', models.CharField(blank=True)),
                ('kpp', models.CharField(blank=True)),
                ('address', models.CharField(blank=True)),
                ('manager_fio', models.CharField(blank=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upd.seller')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True)),
                ('number', models.CharField(blank=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True)),
                ('name', models.CharField(blank=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_signed', models.BooleanField(blank=True)),
                ('other', models.CharField(blank=True)),
                ('resp_position', models.CharField(blank=True)),
                ('resp_name', models.CharField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentCreator',
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='sellerbuyer_id',
        ),
        migrations.DeleteModel(
            name='TransferDetails',
        ),
        migrations.DeleteModel(
            name='SellerBuyer',
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
