# Generated by Django 5.2.1 on 2025-05-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='is_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_adjusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='relation_type',
            field=models.CharField(choices=[('1', 'Он же'), ('2', 'Другая организация'), ('3', 'Не указывать')], max_length=1),
        ),
    ]
