# Generated by Django 5.2.1 on 2025-05-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0005_alter_shipping_address_alter_shipping_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='inn',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='kpp',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='manager_fio',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='relation_type',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_type',
            field=models.CharField(),
        ),
    ]
