# Generated by Django 5.2.1 on 2025-05-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0009_alter_additionalinfo_nds_activ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdetails',
            name='is_signed',
            field=models.BooleanField(),
        ),
    ]
