# Generated by Django 5.2.1 on 2025-05-25 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0014_alter_documents_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdetails',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
