# Generated by Django 5.2.1 on 2025-05-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0015_alter_transferdetails_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='number',
            new_name='invoice_number',
        ),
    ]
