# Generated by Django 5.2.1 on 2025-05-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_identifier', models.CharField()),
                ('document_type', models.CharField()),
                ('vat_rate', models.CharField()),
                ('currency', models.CharField()),
                ('form_format', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_advance', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField()),
                ('name', models.CharField()),
                ('inn', models.CharField()),
                ('kpp', models.CharField()),
                ('type', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('number', models.CharField()),
                ('date', models.DateField()),
                ('type', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField()),
                ('transportation_data', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField()),
                ('date', models.DateField()),
                ('is_adjusted', models.BinaryField()),
                ('adjusted_number', models.CharField()),
                ('adjusted_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OutputSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_stamp', models.BinaryField()),
                ('show_signature', models.BinaryField()),
                ('file_format', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='SellerBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
                ('status', models.CharField()),
                ('name', models.CharField()),
                ('full_name', models.CharField()),
                ('inn', models.CharField()),
                ('kpp', models.CharField()),
                ('reg_address', models.CharField()),
                ('address', models.CharField()),
                ('requisite', models.CharField()),
                ('manager', models.CharField()),
                ('manager_fio', models.CharField()),
                ('accountant_fio', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='TransferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('type', models.CharField()),
                ('position', models.CharField()),
                ('date', models.DateField()),
                ('is_signed', models.BinaryField()),
                ('other', models.CharField()),
                ('resp_name', models.CharField()),
                ('resp_position', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('article', models.CharField()),
                ('quantity', models.CharField()),
                ('unit', models.CharField()),
                ('customs_code', models.CharField()),
                ('customs_type_code', models.CharField()),
                ('country_code', models.CharField()),
                ('country_name', models.CharField()),
                ('customs_declaration_num', models.CharField()),
                ('price', models.FloatField()),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upd.section')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_type', models.CharField()),
                ('relation_type', models.CharField()),
                ('name', models.CharField()),
                ('inn', models.CharField()),
                ('kpp', models.CharField()),
                ('address', models.CharField()),
                ('manager_fio', models.CharField()),
                ('sellerbuyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upd.sellerbuyer')),
            ],
        ),
    ]
