# Generated by Django 5.2.1 on 2025-05-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0002_alter_advancepayment_is_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='excise_duty',
            field=models.CharField(default='', max_length=50),
        ),
    ]
