# Generated by Django 5.2.1 on 2025-05-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0003_product_excise_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='excise_duty',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='relation_type',
            field=models.CharField(),
        ),
    ]
