# Generated by Django 5.2.1 on 2025-05-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0008_additionalinfo_nds_activ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='nds_activ',
            field=models.CharField(),
        ),
    ]
