# Generated by Django 5.2.1 on 2025-05-25 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0012_alter_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='adjusted_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
